[package]
name = "timings_factors"
version = "0.1.0"
authors = ["Robbie Bykowski <robbie.bykowski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primes = "0.3.0"